spring.application.name=opticyou

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:1111/opticyou
spring.datasource.username=admin
spring.datasource.password=ioc

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (si usas JPA)
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


