server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/opticyou  # la BD
    username: admin
    password: ioc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    user:
      password: 1234
    jwt:
      secret-key: d3eC8t6C0f5sG9zS7kL4pQ2rVb1B8wXn #aixo hauria de ser privat i tal, però de moment es queda així
      expiration: 86400000
      refresh-token:
        expiration: 604800000