server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/opticyou  # la BD
    username: admin
    password: ioc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.auto: update
      jakarta.persistence.jdbc.url: jdbc:postgresql://localhost:1111/opticyou
  security:
    user:
      password: 1234
    jwt:
      secret-key: ZOC1FhG1EJ4UZRFjZv55lIw/BqGtRdQ7J+aZ3eQkQ8P9h3BLH0cNTT1flP1B6Pe5 #aixo hauria de ser privat i tal, però de moment es queda així
      expiration: 86400000
      refresh-token:
        expiration: 604800000