server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/opticyou  # la BD
    username: admin
    password: ioc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    user:
      password: 1234
